export const specialEvents = new Map<string, string>()
specialEvents.set('bindtimeupdate', 'onTimeUpdate')
specialEvents.set('bindgetphoneNumber', 'onGetPhoneNumber')
specialEvents.set('bindchooseavatar', 'onChooseAvatar')
specialEvents.set('bindgetrealnameauthinfo', 'onGetRealnameAuthInfo')
specialEvents.set('bindopensetting', 'onOpenSetting')
specialEvents.set('bindscancode', 'onScanCode')
specialEvents.set('bindstatechange', 'onStateChange')
specialEvents.set('bindhtouchmove', 'onHTouchMove')
specialEvents.set('bindvtouchmove', 'onVTouchMove')
specialEvents.set('bindcolumnchange', 'onColumnChange')
specialEvents.set('bindscrolltoupper', 'onScrollToUpper')
specialEvents.set('bindscrolltolower', 'onScrollToLower')
specialEvents.set('bindanimationfinish', 'onAnimationFinish')
specialEvents.set('bindfullscreenchange', 'onFullscreenChange')
specialEvents.set('bindtouchstart', 'onTouchStart')
specialEvents.set('bindtouchmove', 'onTouchMove')
specialEvents.set('bindtouchcancel', 'onTouchCancel')
specialEvents.set('bindtouchend', 'onTouchEnd')
specialEvents.set('bindlongpress', 'onLongPress')
specialEvents.set('bindlongclick', 'onLongClick')
specialEvents.set('bindtransitionend', 'onTransitionEnd')
specialEvents.set('bindanimationstart', 'onAnimationStart')
specialEvents.set('bindanimationtteration', 'onAnimationIteration')
specialEvents.set('bindanimationend', 'onAnimationEnd')
specialEvents.set('bindtouchforcechange', 'onTouchForceChange')
specialEvents.set('bindtap', 'onClick')
specialEvents.forEach((value, key) => {
  specialEvents.set(key.replace(/^bind/, 'catch'), value)
})

export const specialSameEvents = new Map<string, string>()
specialSameEvents.set('bind:timeupdate', 'onTimeUpdate')
specialSameEvents.set('bind:getphoneNumber', 'onGetPhoneNumber')
specialSameEvents.set('bind:chooseavatar', 'onChooseAvatar')
specialSameEvents.set('bind:getrealnameauthinfo', 'onGetRealnameAuthInfo')
specialSameEvents.set('bind:opensetting', 'onOpenSetting')
specialSameEvents.set('bind:scancode', 'onScanCode')
specialSameEvents.set('bind:statechange', 'onStateChange')
specialSameEvents.set('bind:htouchmove', 'onHTouchMove')
specialSameEvents.set('bind:vtouchmove', 'onVTouchMove')
specialSameEvents.set('bind:columnchange', 'onColumnChange')
specialSameEvents.set('bind:scrolltoupper', 'onScrollToUpper')
specialSameEvents.set('bind:scrolltolower', 'onScrollToLower')
specialSameEvents.set('bind:animationfinish', 'onAnimationFinish')
specialSameEvents.set('bind:fullscreenchange', 'onFullscreenChange')
specialSameEvents.set('bind:touchstart', 'onTouchStart')
specialSameEvents.set('bind:touchmove', 'onTouchMove')
specialSameEvents.set('bind:touchcancel', 'onTouchCancel')
specialSameEvents.set('bind:touchend', 'onTouchEnd')
specialSameEvents.set('bind:longpress', 'onLongPress')
specialSameEvents.set('bind:longclick', 'onLongClick')
specialSameEvents.set('bind:transitionend', 'onTransitionEnd')
specialSameEvents.set('bind:animationstart', 'onAnimationStart')
specialSameEvents.set('bind:animationtteration', 'onAnimationIteration')
specialSameEvents.set('bind:animationend', 'onAnimationEnd')
specialSameEvents.set('bind:touchforcechange', 'onTouchForceChange')
specialSameEvents.set('bind:tap', 'onClick')
specialSameEvents.forEach((value, key) => {
  specialSameEvents.set(key.replace(/^bind/, 'catch'), value)
})