name: codecheck

on:
  push:
    branches:
      - release-3.6.8-app
  pull_request:
    branches:
      - release-3.6.8-app

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
               
      - name: lint
        run: pnpm lint
     
